server:
  port: 8070
spring:
  config:
    activate:
      on-profile: "docker"
    import: "optional:configserver:"
  application:
    name: gateway-server
  cloud:
    config:
      enabled: true
      uri: http://config-server:8080
      request-read-timeout: 1000
      request-connect-timeout: 100
