spring:
  config:
    activate:
      on-profile: "docker"
    import: "optional:configserver:"
  application:
    name: eureka-server
  cloud:
    config:
      enabled: true
      uri: http://config-server:8080
      request-read-timeout: 1000
      request-connect-timeout: 100

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761