spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/app/config/
        encrypt:
          enabled: true
server:
  port: 8080

encrypt:
  key: SECU200