logging:
  file:
    name: logs/gateway-log.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.msa.gatewayserver: debug

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ITEM-SERVICE
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/vi/item/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
