logging:
  file:
    name: logs/gateway-log.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.msa.gatewayserver: debug
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.route: DEBUG

spring:
  config:
    import:
      - classpath:/config/datasource-docker.yml
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: ITEM-SERVICE
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/vi/item/**
          filters:
            - RewritePath=/vi/item/(?<segment>.*), /vi/item/${segment}
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans