logging:
  file:
    name: logs/api-test-react7.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.msa.item: debug

spring:
  config:
    import:
      - classpath:/config/datasource-docker.yml

token:
  expiration_time: 86400000
  secret: SECU200

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
